server:
  port: 9091

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: user-service-docs
          uri: lb://USER-SERVICE
          predicates:
            - Path=/v3/api-docs/user-service    
            
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
        - id: product-service-docs
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/v3/api-docs/product-service     
            
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**
        - id: order-service-docs
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/v3/api-docs/order-service    

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
        - id: payment-service-docs
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/v3/api-docs/payment-service       
      discovery:
         enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: localhost 
    
    
      
#For Zipkin   
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9412/api/v2/spans



